apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: echo-server
spec:
  title: echo-server
  statusInformers:
    - deployment/echo-server
  ports:
    - serviceName: "echo-server"
      servicePort: 3000
      localPort: 8888
      applicationUrl: "http://echo-server"
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
