  apiVersion: kots.io/v1beta1
  kind: Config
  metadata:
    name: echo-server-config
  spec:
    groups:
      - name: echo-server
        title: echo-server
        description: echo-server Configuration
        items:
          - name: admin_user
            title: Admin User
            type: text
            default: 'admin'
          - name: admin_password
            title: Admin Password
            type: password
            default: 'admin'
