name: Airgap Build and Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the chart to test'
        required: true
        default: '0.2.0'

env:
  chart_name: replibot
  app_id: 
        

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_SLUG: "dexter-test3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Channel Release Sequence
        id: get-channel-release-sequence
        run: |
          curl --request GET \
            --url https://api.replicated.com/vendor/v3/app/${{ secrets.REPLICATED_APP_ID }}/channel/2pusnQ3dbpDq0SEVEE8LCeUCCwC/releases \
            --header 'Authorization: ${{ secrets.REPLICATED_API_TOKEN }}' \
            --header 'accept: application/json' | jq -r '.releases[0].channelSequence' > channel-release-sequence.txt
          cat channel-release-sequence.txt
          echo "channel-release-sequence=$(cat channel-release-sequence.txt)" >> $GITHUB_OUTPUT
    
      - name: build airgap
        run: |
          curl --request POST \
            --url https://api.replicated.com/vendor/v3/app/${{ secrets.REPLICATED_APP_ID }}/channel/2pusnQ3dbpDq0SEVEE8LCeUCCwC/release/${{ steps.get-channel-release-sequence.outputs.channel-release-sequence }}/airgap/build \
            --header 'Authorization: ${{ secrets.REPLICATED_API_TOKEN }}' \
            --header 'accept: application/json'
