name: Build and Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the chart to test'
        required: true
        default: '0.2.0'

env:
  chart_name: replibot


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker buildx build . --platform linux/amd64,linux/arm64 -t replibot-testing:${{ github.event.inputs.version }} --push

      


        
