name: Build and Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the chart to test'
        required: true
        default: '0.2.0'

env:
  chart_name: echo-server
  app_id: 2S2KBYYp3fKkP42pb3eJYIYJNYv
  channel_name: echo

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_SLUG: "dexter-test3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Package Helm Chart
        run: helm package helm/${{ env.chart_name }} -d helm/manifests
      
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-package
          path: helm/manifests
          retention-days: 1
  
      - name: create-release
        id: create-release
        uses: replicatedhq/replicated-actions/create-cluster@dx/sc-120959/update-create-release
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          app-slug: ${{ env.APP_SLUG }}
          yaml-dir: ./helm/manifests
          promote-channel: echo
          version: ${{ github.event.inputs.version }}
          wait-for-airgap-build: true

      - name: echo airgap build status
        run: |
          echo "airgap build status: ${{ steps.create-release.outputs.airgap-build-status }}"
          echo "airgap url: ${{ steps.create-release.outputs.airgap-url }}"
