name: Build and Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the chart to test'
        required: true
        default: '0.2.0'

env:
  chart_name: replibot


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_SLUG: "dexter-test3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: dexteryanreplicated/replibot-testing:${{ github.event.inputs.version }}
      
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        run: helm package helm/${{ env.chart_name }} -d helm/manifests
      
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: helm-package
          path: helm/manifests
          retention-days: 1
  
      - name: create-release
        id: create-release
        uses: replicatedhq/replicated-actions/create-release@v1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          app-slug: ${{ env.APP_SLUG }}
          yaml-dir: ./helm/manifests
          promote-channel: Replibot
          version: ${{ github.event.inputs.version }}
      
